### ISSUE TITLE
Assertion error on platforms where size of 'long' struct is 4 bytes

### ISSUE THREAD

**Issue by roganov** [tailhook/cantal-py#2]
https://github.com/tailhook/cantal-py/blob/master/cantal/simple_state.py#L16

Not sure if this is a bug or by design, but `struct.Struct('L')` is not guaranteed to be of 8 bytes. Moreover, the 'standard size' is 4 bytes according to the python docs: https://docs.python.org/3.5/library/struct.html#format-characters

**Comment by tailhook** [comment]
You're right. I've never run production on anything other than x86_84 for about 7 years. So it's not a critical but for me.

Still pull requests are accepted (but you should at least run tests on i386 to ensure that this bug is gone)
